package com.etnet.coresdk.coreConfig;

import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

import com.etnet.coresdk.coreModel.DecoderInfo;
import com.etnet.coresdk.coreStorage.data.decoder.BidAskDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.BidAskQtyDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.BidAskSummaryAShareDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.BrokerQueueDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.BuySellDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.ChartWarDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.CodeDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.DailyQuotaDataDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.DayChartDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.DoubleDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.FluctuationDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.FutureDepthDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.HotSectorDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.IndustryAnalysisDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.LimitDownDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.LimitUpDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.LongDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.MemoDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.MinuteChartDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.MoneyFlowDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.MonthlyQuotaDataDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.OptionDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.OrderRatioAHDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.OrderRatioDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.PriceUpDownDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.RegionDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.ShortSellDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.SpeBroDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.SpeFlowDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.SpeStkDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.StringDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.SummaryQueueDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.TickChartDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.TimeDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.Top10StockConnectTurnoverDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.TransSummaryDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.TransactionDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.TurnoverCBBCDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.TurnoverRateDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.TurnoverWarrDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.VcmTriggerDecoder;
import com.etnet.coresdk.coreStorage.data.decoder.VcmTriggerPeriodDecoder;

import static com.etnet.coresdk.api.ApiFields.*;

public class DefaultDecoderConfig {
    public static final Map<String, DecoderInfo> DefaultDecoderConfig = new HashMap<String, DecoderInfo>() {{
        put(FID_CODE, new DecoderInfo(FID_CODE, null, FKEY_CODE, CodeDecoder.uniqueID, new CodeDecoder()));
        put(FID_TC_NAME, new DecoderInfo(FID_TC_NAME, null, FKEY_TC_NAME, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_SC_NAME, new DecoderInfo(FID_SC_NAME, null, FKEY_SC_NAME, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_EN_NAME, new DecoderInfo(FID_EN_NAME, null, FKEY_EN_NAME, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_SMA_10, new DecoderInfo(FID_SMA_10, null, FKEY_SMA_10, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_SMA_20, new DecoderInfo(FID_SMA_20, null, FKEY_SMA_20, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_SMA_50, new DecoderInfo(FID_SMA_50, null, FKEY_SMA_50, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_SMA_250, new DecoderInfo(FID_SMA_250, null, FKEY_SMA_250, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_1M_HIGH, new DecoderInfo(FID_1M_HIGH, null, FKEY_1M_HIGH, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_1M_LOW, new DecoderInfo(FID_1M_LOW, null, FKEY_1M_LOW, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_52W_HIGH, new DecoderInfo(FID_52W_HIGH, null, FKEY_52W_HIGH, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_52W_LOW, new DecoderInfo(FID_52W_LOW, null, FKEY_52W_LOW, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_MARKET, new DecoderInfo(FID_MARKET, null, FKEY_MARKET, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_INDUSTRY_REL, new DecoderInfo(FID_INDUSTRY_REL, null, FKEY_INDUSTRY_REL, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_INDEX_REL, new DecoderInfo(FID_INDEX_REL, null, FKEY_INDEX_REL, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_SECURITY_TYPE, new DecoderInfo(FID_SECURITY_TYPE, null, FKEY_SECURITY_TYPE, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_HV20, new DecoderInfo(FID_HV20, null, FKEY_HV20, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_MARKET_CAP, new DecoderInfo(FID_MARKET_CAP, null, FKEY_MARKET_CAP, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_M_NAV, new DecoderInfo(FID_M_NAV, null, FKEY_M_NAV, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_EXERCISE_PRICE, new DecoderInfo(FID_EXERCISE_PRICE, null, FKEY_EXERCISE_PRICE, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_EXPIRY_DATE, new DecoderInfo(FID_EXPIRY_DATE, null, FKEY_EXPIRY_DATE, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_ENTITLEMENT_RATIO, new DecoderInfo(FID_ENTITLEMENT_RATIO, null, FKEY_ENTITLEMENT_RATIO, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_ISSUER_NAME_TC, new DecoderInfo(FID_ISSUER_NAME_TC, null, FKEY_ISSUER_NAME_TC, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_ISSUER_NAME_SC, new DecoderInfo(FID_ISSUER_NAME_SC, null, FKEY_ISSUER_NAME_SC, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_ISSUER_NAME_EN, new DecoderInfo(FID_ISSUER_NAME_EN, null, FKEY_ISSUER_NAME_EN, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_LP_CODE, new DecoderInfo(FID_LP_CODE, null, FKEY_LP_CODE, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_WARRANT_TYPE, new DecoderInfo(FID_WARRANT_TYPE, null, FKEY_WARRANT_TYPE, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_CALL_PRICE, new DecoderInfo(FID_CALL_PRICE, null, FKEY_CALL_PRICE, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_CBBC_TYPE, new DecoderInfo(FID_CBBC_TYPE, null, FKEY_CBBC_TYPE, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_SR_RU, new DecoderInfo(FID_SR_RU, null, FKEY_SR_RU, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_CBBC_RELATION, new DecoderInfo(FID_CBBC_RELATION, null, FKEY_CBBC_RELATION, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_WARR_RELATION, new DecoderInfo(FID_WARR_RELATION, null, FKEY_WARR_RELATION, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_NOMINAL, new DecoderInfo(FID_NOMINAL, null, FKEY_NOMINAL, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_PER_CHANGE, new DecoderInfo(FID_PER_CHANGE, null, FKEY_PER_CHANGE, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_TURNOVER, new DecoderInfo(FID_TURNOVER, null, FKEY_TURNOVER, LongDecoder.uniqueId, new LongDecoder()));
        put(FID_VOLUME, new DecoderInfo(FID_VOLUME, null, FKEY_VOLUME, LongDecoder.uniqueId, new LongDecoder()));
        put(FID_NO_OF_TRANS, new DecoderInfo(FID_NO_OF_TRANS, null, FKEY_NO_OF_TRANS, LongDecoder.uniqueId, new LongDecoder()));
        put(FID_CHANGE, new DecoderInfo(FID_CHANGE, null, FKEY_CHANGE, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_HIGH, new DecoderInfo(FID_HIGH, null, FKEY_HIGH, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_LOW, new DecoderInfo(FID_LOW, null, FKEY_LOW, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_PE_RATIO, new DecoderInfo(FID_PE_RATIO, null, FKEY_PE_RATIO, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_DPS, new DecoderInfo(FID_DPS, null, FKEY_DPS, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_EPS, new DecoderInfo(FID_EPS, null, FKEY_EPS, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_EXPECT_EPS, new DecoderInfo(FID_EXPECT_EPS, null, FKEY_EXPECT_EPS, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_EXPECT_DPS, new DecoderInfo(FID_EXPECT_DPS, null, FKEY_EXPECT_DPS, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_EM_NAV, new DecoderInfo(FID_EM_NAV, null, FKEY_EM_NAV, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_CLOSE, new DecoderInfo(FID_CLOSE, null, FKEY_CLOSE, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_IEP, new DecoderInfo(FID_IEP, null, FKEY_IEP, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_IEV, new DecoderInfo(FID_IEV, null, FKEY_IEV, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_ASK, new DecoderInfo(FID_ASK, null, FKEY_ASK, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_BID, new DecoderInfo(FID_BID, null, FKEY_BID, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_OPEN, new DecoderInfo(FID_OPEN, null, FKEY_OPEN, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_PERCENT_YIELD, new DecoderInfo(FID_PERCENT_YIELD, null, FKEY_PERCENT_YIELD, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_EXPECT_PERCENT_YIELD, new DecoderInfo(FID_EXPECT_PERCENT_YIELD, null, FKEY_EXPECT_PERCENT_YIELD, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_EXPECT_PE_RATIO, new DecoderInfo(FID_EXPECT_PE_RATIO, null, FKEY_EXPECT_PE_RATIO, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_WEIGHTED_AVG, new DecoderInfo(FID_WEIGHTED_AVG, null, FKEY_WEIGHTED_AVG, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_VOLUME_RATIO, new DecoderInfo(FID_VOLUME_RATIO, null, FKEY_VOLUME_RATIO, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_VOLUME_T, new DecoderInfo(FID_VOLUME_T, null, FKEY_VOLUME_T, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_AMT_T, new DecoderInfo(FID_AMT_T, null, FKEY_AMT_T, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_PERCENT_M_NAV, new DecoderInfo(FID_PERCENT_M_NAV, null, FKEY_PERCENT_M_NAV, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_EXPECT_NET_PROFIT, new DecoderInfo(FID_EXPECT_NET_PROFIT, null, FKEY_EXPECT_NET_PROFIT, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_PERCENT_IV, new DecoderInfo(FID_PERCENT_IV, null, FKEY_PERCENT_IV, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_CONVERSION_COST, new DecoderInfo(FID_CONVERSION_COST, null, FKEY_CONVERSION_COST, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_DELTA, new DecoderInfo(FID_DELTA, null, FKEY_DELTA, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_GEARING_RATIO, new DecoderInfo(FID_GEARING_RATIO, null, FKEY_GEARING_RATIO, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_EFF_GEARING_RATIO, new DecoderInfo(FID_EFF_GEARING_RATIO, null, FKEY_EFF_GEARING_RATIO, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_DAYS_TO_EXPIRY, new DecoderInfo(FID_DAYS_TO_EXPIRY, null, FKEY_DAYS_TO_EXPIRY, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_LAST_TRADE_DATE, new DecoderInfo(FID_LAST_TRADE_DATE, null, FKEY_LAST_TRADE_DATE, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_LP_BUY_VOL, new DecoderInfo(FID_LP_BUY_VOL, null, FKEY_LP_BUY_VOL, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_LP_BUY_PRICE, new DecoderInfo(FID_LP_BUY_PRICE, null, FKEY_LP_BUY_PRICE, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_LP_SOLD_VOL, new DecoderInfo(FID_LP_SOLD_VOL, null, FKEY_LP_SOLD_VOL, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_LP_SOLD_PRICE, new DecoderInfo(FID_LP_SOLD_PRICE, null, FKEY_LP_SOLD_PRICE, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_OUTSTAND_QUAN, new DecoderInfo(FID_OUTSTAND_QUAN, null, FKEY_OUTSTAND_QUAN, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_PERCENT_OUTSTAND_QUAN, new DecoderInfo(FID_PERCENT_OUTSTAND_QUAN, null, FKEY_PERCENT_OUTSTAND_QUAN, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_UNITS_ISSUED, new DecoderInfo(FID_UNITS_ISSUED, null, FKEY_UNITS_ISSUED, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_SHORTSELL, new DecoderInfo(FID_SHORTSELL, null, FKEY_SHORTSELL, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_PERCENT_SHORTSELL, new DecoderInfo(FID_PERCENT_SHORTSELL, null, FKEY_PERCENT_SHORTSELL, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_PERCENT_PREMIUM, new DecoderInfo(FID_PERCENT_PREMIUM, null, FKEY_PERCENT_PREMIUM, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_AVAILABLE_TRADINGDAY, new DecoderInfo(FID_AVAILABLE_TRADINGDAY, null, FKEY_AVAILABLE_TRADINGDAY, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_SUMMARY_QUEUE, new DecoderInfo(FID_SUMMARY_QUEUE, null, FKEY_SUMMARY_QUEUE, SummaryQueueDecoder.uniqueId, new SummaryQueueDecoder()));
        put(FID_BROKER_QUEUE, new DecoderInfo(FID_BROKER_QUEUE, null, FKEY_BROKER_QUEUE, BrokerQueueDecoder.uniqueId, new BrokerQueueDecoder()));
        put(FID_BOARDLOT, new DecoderInfo(FID_BOARDLOT, null, FKEY_BOARDLOT, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_CURRENCY, new DecoderInfo(FID_CURRENCY, null, FKEY_CURRENCY, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_SPREAD, new DecoderInfo(FID_SPREAD, null, FKEY_SPREAD, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_BIDASK_FORCE_BAR, new DecoderInfo(FID_BIDASK_FORCE_BAR, null, FKEY_BIDASK_FORCE_BAR, BidAskDecoder.uniqueId, new BidAskDecoder()));
        put(FID_BUYSELL_TRN_FORCE_BAR, new DecoderInfo(FID_BUYSELL_TRN_FORCE_BAR, null, FKEY_BUYSELL_TRN_FORCE_BAR, BuySellDecoder.uniqueId, new BuySellDecoder()));
        put(FID_IND_BUYSELL_FORCE_BAR, new DecoderInfo(FID_IND_BUYSELL_FORCE_BAR, null, FKEY_IND_BUYSELL_FORCE_BAR, BuySellDecoder.uniqueId, new BuySellDecoder()));
        put(FID_ADR_CLOSE_HKD, new DecoderInfo(FID_ADR_CLOSE_HKD, null, FKEY_ADR_CLOSE_HKD, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_ADR_PERCENT_CHG, new DecoderInfo(FID_ADR_PERCENT_CHG, null, FKEY_ADR_PERCENT_CHG, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_PRICE_UP_DOWN, new DecoderInfo(FID_PRICE_UP_DOWN, null, FKEY_PRICE_UP_DOWN, PriceUpDownDecoder.uniqueId, new PriceUpDownDecoder()));
        put(FID_UNDERLYING_CBBC_TRN, new DecoderInfo(FID_UNDERLYING_CBBC_TRN, null, FKEY_UNDERLYING_CBBC_TRN, TurnoverCBBCDecoder.uniqueId, new TurnoverCBBCDecoder()));
        put(FID_UNDERLYING_WAR_TRN, new DecoderInfo(FID_UNDERLYING_WAR_TRN, null, FKEY_UNDERLYING_WAR_TRN, TurnoverWarrDecoder.uniqueId, new TurnoverWarrDecoder()));
        put(FID_D52WK_N_HIGH, new DecoderInfo(FID_D52WK_N_HIGH, null, FKEY_D52WK_N_HIGH, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_D52WK_N_LOW, new DecoderInfo(FID_D52WK_N_LOW, null, FKEY_D52WK_N_LOW, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_FREE_TEXT, new DecoderInfo(FID_FREE_TEXT, null, FKEY_FREE_TEXT, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_IND_BS_TRN_FORCE_BAR, new DecoderInfo(FID_IND_BS_TRN_FORCE_BAR, null, FKEY_IND_BS_TRN_FORCE_BAR, BuySellDecoder.uniqueId, new BuySellDecoder()));
        put(FID_WAR_PER_OUT_QTY, new DecoderInfo(FID_WAR_PER_OUT_QTY, null, FKEY_WAR_PER_OUT_QTY, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_CBBC_PER_OUT_QTY, new DecoderInfo(FID_CBBC_PER_OUT_QTY, null, FKEY_CBBC_PER_OUT_QTY, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_WAR_OUT_QTY, new DecoderInfo(FID_WAR_OUT_QTY, null, FKEY_WAR_OUT_QTY, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_CBBC_OUT_QTY, new DecoderInfo(FID_CBBC_OUT_QTY, null, FKEY_CBBC_OUT_QTY, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_INDUSTRY_TRN, new DecoderInfo(FID_INDUSTRY_TRN, null, FKEY_INDUSTRY_TRN, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_INDUSTRY_PER_MT, new DecoderInfo(FID_INDUSTRY_PER_MT, null, FKEY_INDUSTRY_PER_MT, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_RATE, new DecoderInfo(FID_RATE, null, FKEY_RATE, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_PREMIUM, new DecoderInfo(FID_PREMIUM, null, FKEY_PREMIUM, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_WAR_NEW_LISTING, new DecoderInfo(FID_WAR_NEW_LISTING, null, FKEY_WAR_NEW_LISTING, MemoDecoder.uniqueId, new MemoDecoder()));
        put(FID_CBBC_NEW_LISTING, new DecoderInfo(FID_CBBC_NEW_LISTING, null, FKEY_CBBC_NEW_LISTING, MemoDecoder.uniqueId, new MemoDecoder()));
        put(FID_WAR_EXPIRING, new DecoderInfo(FID_WAR_EXPIRING, null, FKEY_WAR_EXPIRING, MemoDecoder.uniqueId, new MemoDecoder()));
        put(FID_CBBC_EXPIRING, new DecoderInfo(FID_CBBC_EXPIRING, null, FKEY_CBBC_EXPIRING, MemoDecoder.uniqueId, new MemoDecoder()));
        put(FID_CBBC_KNOCKOUTS, new DecoderInfo(FID_CBBC_KNOCKOUTS, null, FKEY_CBBC_KNOCKOUTS, MemoDecoder.uniqueId, new MemoDecoder()));
        put(FID_CBBC_HIGHRISK, new DecoderInfo(FID_CBBC_HIGHRISK, null, FKEY_CBBC_HIGHRISK, MemoDecoder.uniqueId, new MemoDecoder()));
        put(FID_PRV_DAY_TRN, new DecoderInfo(FID_PRV_DAY_TRN, null, FKEY_PRV_DAY_TRN, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_PRV_DAY_TRN_MT, new DecoderInfo(FID_PRV_DAY_TRN_MT, null, FKEY_PRV_DAY_TRN_MT, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_UP_LIMIT, new DecoderInfo(FID_UP_LIMIT, null, FKEY_UP_LIMIT, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_DOWN_LIMIT, new DecoderInfo(FID_DOWN_LIMIT, null, FKEY_DOWN_LIMIT, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_SINGLE_QTY, new DecoderInfo(FID_SINGLE_QTY, null, FKEY_SINGLE_QTY, BidAskQtyDecoder.uniqueId, new BidAskQtyDecoder()));
        put(FID_FUTURE_QUEUE, new DecoderInfo(FID_FUTURE_QUEUE, null, FKEY_FUTURE_QUEUE, FutureDepthDecoder.uniqueId, new FutureDepthDecoder()));
        put(FID_LAST_QTY, new DecoderInfo(FID_LAST_QTY, null, FKEY_LAST_QTY, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_LAST_INDICATOR, new DecoderInfo(FID_LAST_INDICATOR, null, FKEY_LAST_INDICATOR, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_PRV_VOL, new DecoderInfo(FID_PRV_VOL, null, FKEY_PRV_VOL, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_CHG_VOL, new DecoderInfo(FID_CHG_VOL, null, FKEY_CHG_VOL, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_GOI, new DecoderInfo(FID_GOI, null, FKEY_GOI, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_NOI, new DecoderInfo(FID_NOI, null, FKEY_NOI, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_CHG_GOI, new DecoderInfo(FID_CHG_GOI, null, FKEY_CHG_GOI, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_CHG_NOI, new DecoderInfo(FID_CHG_NOI, null, FKEY_CHG_NOI, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_EAS, new DecoderInfo(FID_EAS, null, FKEY_EAS, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_TIME, new DecoderInfo(FID_TIME, null, FKEY_TIME, TimeDecoder.uniqueId, new TimeDecoder()));
        put(FID_L_HIGH, new DecoderInfo(FID_L_HIGH, null, FKEY_L_HIGH, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_L_LOW, new DecoderInfo(FID_L_LOW, null, FKEY_L_LOW, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_TTL_VOL, new DecoderInfo(FID_TTL_VOL, null, FKEY_TTL_VOL, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_TTL_PRV_VOL, new DecoderInfo(FID_TTL_PRV_VOL, null, FKEY_TTL_PRV_VOL, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_TTL_GOI, new DecoderInfo(FID_TTL_GOI, null, FKEY_TTL_GOI, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_TTL_NOI, new DecoderInfo(FID_TTL_NOI, null, FKEY_TTL_NOI, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_TTL_CHG_GOI, new DecoderInfo(FID_TTL_CHG_GOI, null, FKEY_TTL_CHG_GOI, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_TTL_CHG_NOI, new DecoderInfo(FID_TTL_CHG_NOI, null, FKEY_TTL_CHG_NOI, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_COMBO_SERIES, new DecoderInfo(FID_COMBO_SERIES, null, FKEY_COMBO_SERIES, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_FPP_1M, new DecoderInfo(FID_FPP_1M, null, FKEY_FPP_1M, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_FPP_3M, new DecoderInfo(FID_FPP_3M, null, FKEY_FPP_3M, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_FPP_6M, new DecoderInfo(FID_FPP_6M, null, FKEY_FPP_6M, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_FPP_1Y, new DecoderInfo(FID_FPP_1Y, null, FKEY_FPP_1Y, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_AVG_PER_CHANGE, new DecoderInfo(FID_AVG_PER_CHANGE, null, FKEY_AVG_PER_CHANGE, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_BIDASK_FORCEBAR_NORMAL, new DecoderInfo(FID_BIDASK_FORCEBAR_NORMAL, null, FKEY_BIDASK_FORCEBAR_NORMAL, BidAskDecoder.uniqueId, new BidAskDecoder()));
        put(FID_PRC_UPDOWN_NOCHG_NOTRN, new DecoderInfo(FID_PRC_UPDOWN_NOCHG_NOTRN, null, FKEY_PRC_UPDOWN_NOCHG_NOTRN, PriceUpDownDecoder.uniqueId, new PriceUpDownDecoder()));
        put(FID_PER_MONEYNESS, new DecoderInfo(FID_PER_MONEYNESS, null, FKEY_PER_MONEYNESS, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_STOCK2SPREADTABLE, new DecoderInfo(FID_STOCK2SPREADTABLE, null, FKEY_STOCK2SPREADTABLE, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_PERCHG_TO_CALLPRC, new DecoderInfo(FID_PERCHG_TO_CALLPRC, null, FKEY_PERCHG_TO_CALLPRC, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_CHG_TO_CALLPRC, new DecoderInfo(FID_CHG_TO_CALLPRC, null, FKEY_CHG_TO_CALLPRC, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_ISSUER_PRICE, new DecoderInfo(FID_ISSUER_PRICE, null, FKEY_ISSUER_PRICE, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_PROSTICKS_MODAL_PT, new DecoderInfo(FID_PROSTICKS_MODAL_PT, null, FKEY_PROSTICKS_MODAL_PT, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_PROSTICKS_MODAL_COUNT, new DecoderInfo(FID_PROSTICKS_MODAL_COUNT, null, FKEY_PROSTICKS_MODAL_COUNT, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_PROSTICKS_ACT_RANGE_UP, new DecoderInfo(FID_PROSTICKS_ACT_RANGE_UP, null, FKEY_PROSTICKS_ACT_RANGE_UP, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_PROSTICKS_ACT_RANGE_LOW, new DecoderInfo(FID_PROSTICKS_ACT_RANGE_LOW, null, FKEY_PROSTICKS_ACT_RANGE_LOW, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_NBV, new DecoderInfo(FID_NBV, null, FKEY_NBV, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_CURRENCY_FINSTMT, new DecoderInfo(FID_CURRENCY_FINSTMT, null, FKEY_CURRENCY_FINSTMT, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_NET_PROFIT, new DecoderInfo(FID_NET_PROFIT, null, FKEY_NET_PROFIT, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_CURR_PROFITEST_SUMMARY, new DecoderInfo(FID_CURR_PROFITEST_SUMMARY, null, FKEY_CURR_PROFITEST_SUMMARY, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_LIST_CURRENCY, new DecoderInfo(FID_LIST_CURRENCY, null, FKEY_LIST_CURRENCY, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_LIST_PRICE, new DecoderInfo(FID_LIST_PRICE, null, FKEY_LIST_PRICE, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_LIST_DATE, new DecoderInfo(FID_LIST_DATE, null, FKEY_LIST_DATE, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_ISC, new DecoderInfo(FID_ISC, null, FKEY_ISC, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_EX_DATE, new DecoderInfo(FID_EX_DATE, null, FKEY_EX_DATE, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_PAY_DATE, new DecoderInfo(FID_PAY_DATE, null, FKEY_PAY_DATE, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_ANN_DATE, new DecoderInfo(FID_ANN_DATE, null, FKEY_ANN_DATE, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_RESULT_DATE, new DecoderInfo(FID_RESULT_DATE, null, FKEY_RESULT_DATE, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_EVENT_REMINDAR, new DecoderInfo(FID_EVENT_REMINDAR, null, FKEY_EVENT_REMINDAR, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_DIVIDEND_ANNOUNCEMENT, new DecoderInfo(FID_DIVIDEND_ANNOUNCEMENT, null, FKEY_DIVIDEND_ANNOUNCEMENT, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_DISCLOSURE_INTERESTS, new DecoderInfo(FID_DISCLOSURE_INTERESTS, null, FKEY_DISCLOSURE_INTERESTS, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_FUND_RAISING, new DecoderInfo(FID_FUND_RAISING, null, FKEY_FUND_RAISING, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_SHORTSELL_DATE, new DecoderInfo(FID_SHORTSELL_DATE, null, FKEY_SHORTSELL_DATE, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_ASC, new DecoderInfo(FID_ASC, null, FKEY_ASC, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_NO_ADJ_HIST_HIGH, new DecoderInfo(FID_NO_ADJ_HIST_HIGH, null, FKEY_NO_ADJ_HIST_HIGH, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_NO_ADJ_HIST_LOW, new DecoderInfo(FID_NO_ADJ_HIST_LOW, null, FKEY_NO_ADJ_HIST_LOW, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_ISSUER_INIT_ENG, new DecoderInfo(FID_ISSUER_INIT_ENG, null, FKEY_ISSUER_INIT_ENG, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_ISSUER_INIT_TCHI, new DecoderInfo(FID_ISSUER_INIT_TCHI, null, FKEY_ISSUER_INIT_TCHI, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_ISSUER_INIT_SCHI, new DecoderInfo(FID_ISSUER_INIT_SCHI, null, FKEY_ISSUER_INIT_SCHI, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_CALLED, new DecoderInfo(FID_CALLED, null, FKEY_CALLED, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_TURNOVER_TOP50, new DecoderInfo(FID_TURNOVER_TOP50, null, FKEY_TURNOVER_TOP50, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_CCLOSEAT_1MTH_AGO, new DecoderInfo(FID_CCLOSEAT_1MTH_AGO, null, FKEY_CCLOSEAT_1MTH_AGO, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_CCLOSEAT_3MTHS_AGO, new DecoderInfo(FID_CCLOSEAT_3MTHS_AGO, null, FKEY_CCLOSEAT_3MTHS_AGO, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_CCLOSEAT_6MTHS_AGO, new DecoderInfo(FID_CCLOSEAT_6MTHS_AGO, null, FKEY_CCLOSEAT_6MTHS_AGO, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_CCLOSEAT_12MTHS_AGO, new DecoderInfo(FID_CCLOSEAT_12MTHS_AGO, null, FKEY_CCLOSEAT_12MTHS_AGO, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_D_SUMMARY_QUEUE, new DecoderInfo(FID_D_SUMMARY_QUEUE, null, FKEY_D_SUMMARY_QUEUE, SummaryQueueDecoder.uniqueId, new SummaryQueueDecoder()));
        put(FID_UNDERLYING_ASSET_TC, new DecoderInfo(FID_UNDERLYING_ASSET_TC, null, FKEY_UNDERLYING_ASSET_TC, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_UNDERLYING_ASSET_SC, new DecoderInfo(FID_UNDERLYING_ASSET_SC, null, FKEY_UNDERLYING_ASSET_SC, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_UNDERLYING_ASSET_ENG, new DecoderInfo(FID_UNDERLYING_ASSET_ENG, null, FKEY_UNDERLYING_ASSET_ENG, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_CATEGORY_TC, new DecoderInfo(FID_CATEGORY_TC, null, FKEY_CATEGORY_TC, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_CATEGORY_SC, new DecoderInfo(FID_CATEGORY_SC, null, FKEY_CATEGORY_SC, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_CATEGORY_ENG, new DecoderInfo(FID_CATEGORY_ENG, null, FKEY_CATEGORY_ENG, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_STK_SUSPEND_REMINDER, new DecoderInfo(FID_STK_SUSPEND_REMINDER, null, FKEY_STK_SUSPEND_REMINDER, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_NAV, new DecoderInfo(FID_NAV, null, FKEY_NAV, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_ETF_NAV_DATE, new DecoderInfo(FID_ETF_NAV_DATE, null, FKEY_ETF_NAV_DATE, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_AHFT_MKT_STATUS, new DecoderInfo(FID_AHFT_MKT_STATUS, null, FKEY_AHFT_MKT_STATUS, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_RATIO, new DecoderInfo(FID_RATIO, null, FKEY_RATIO, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_PREFIX_GB_NAME, new DecoderInfo(FID_PREFIX_GB_NAME, null, FKEY_PREFIX_GB_NAME, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_PER_MAX_RISE, new DecoderInfo(FID_PER_MAX_RISE, null, FKEY_PER_MAX_RISE, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_PER_MAX_DECLINE, new DecoderInfo(FID_PER_MAX_DECLINE, null, FKEY_PER_MAX_DECLINE, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_SSUMMARY_QUEUE, new DecoderInfo(FID_SSUMMARY_QUEUE, null, FKEY_SSUMMARY_QUEUE, BidAskSummaryAShareDecoder.uniqueId, new BidAskSummaryAShareDecoder()));
        put(FID_STOCK_CONNECT, new DecoderInfo(FID_STOCK_CONNECT, null, FKEY_STOCK_CONNECT, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_FREE_FLOAT_ISC, new DecoderInfo(FID_FREE_FLOAT_ISC, null, FKEY_FREE_FLOAT_ISC, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_UP_LIMIT_PRICE, new DecoderInfo(FID_UP_LIMIT_PRICE, null, FKEY_UP_LIMIT_PRICE, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_DOWN_LIMIT_PRICE, new DecoderInfo(FID_DOWN_LIMIT_PRICE, null, FKEY_DOWN_LIMIT_PRICE, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_REACH_LIMIT_UPDOWN, new DecoderInfo(FID_REACH_LIMIT_UPDOWN, null, FKEY_REACH_LIMIT_UPDOWN, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_BLK_TRADE_TRN_RATIOBAR, new DecoderInfo(FID_BLK_TRADE_TRN_RATIOBAR, null, FKEY_BLK_TRADE_TRN_RATIOBAR, BuySellDecoder.uniqueId, new BuySellDecoder()));
        put(FID_BLOCK_TURNOVER, new DecoderInfo(FID_BLOCK_TURNOVER, null, FKEY_BLOCK_TURNOVER, LongDecoder.uniqueId, new LongDecoder()));
        put(FID_BLOCK_VOLUME, new DecoderInfo(FID_BLOCK_VOLUME, null, FKEY_BLOCK_VOLUME, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_PB_RATIO, new DecoderInfo(FID_PB_RATIO, null, FKEY_PB_RATIO, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_P_EST_NAV, new DecoderInfo(FID_P_EST_NAV, null, FKEY_P_EST_NAV, LongDecoder.uniqueId, new LongDecoder()));
        put(FID_PREM, new DecoderInfo(FID_PREM, null, FKEY_PREM, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_RSI9, new DecoderInfo(FID_RSI9, null, FKEY_RSI9, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_RSI14, new DecoderInfo(FID_RSI14, null, FKEY_RSI14, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_PERCENT_SHORTSELL, new DecoderInfo(FID_PERCENT_SHORTSELL, null, FKEY_PERCENT_SHORTSELL, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_SHORTSELL5SMA, new DecoderInfo(FID_SHORTSELL5SMA, null, FKEY_SHORTSELL5SMA, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_ETF_PREMIUM, new DecoderInfo(FID_ETF_PREMIUM, null, FKEY_ETF_PREMIUM, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_VCM_TRIGGER, new DecoderInfo(FID_VCM_TRIGGER, null, FKEY_VCM_TRIGGER, VcmTriggerDecoder.uniqueId, new VcmTriggerDecoder()));
        put(FID_VCM_INDICATOR, new DecoderInfo(FID_VCM_INDICATOR, null, FKEY_VCM_INDICATOR, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_CAS_REF_PRICE, new DecoderInfo(FID_CAS_REF_PRICE, null, FKEY_CAS_REF_PRICE, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_IEP_REF_PRC_UPLIMIT, new DecoderInfo(FID_IEP_REF_PRC_UPLIMIT, null, FKEY_IEP_REF_PRC_UPLIMIT, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_IEP_REF_PRC_LOWLIMIT, new DecoderInfo(FID_IEP_REF_PRC_LOWLIMIT, null, FKEY_IEP_REF_PRC_LOWLIMIT, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_CAS_DIRECTION, new DecoderInfo(FID_CAS_DIRECTION, null, FKEY_CAS_DIRECTION, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_CAS_BALANCE_QTY, new DecoderInfo(FID_CAS_BALANCE_QTY, null, FKEY_CAS_BALANCE_QTY, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_CAS_INDICATOR, new DecoderInfo(FID_CAS_INDICATOR, null, FKEY_CAS_INDICATOR, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_TRADE_STATUSID, new DecoderInfo(FID_TRADE_STATUSID, null, FKEY_TRADE_STATUSID, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_VCM_TIME, new DecoderInfo(FID_VCM_TIME, null, FKEY_VCM_TIME, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_VCM_TRIGGER_PERIOD, new DecoderInfo(FID_VCM_TRIGGER_PERIOD, null, FKEY_VCM_TRIGGER_PERIOD, VcmTriggerPeriodDecoder.uniqueId, new VcmTriggerPeriodDecoder()));
        put(FID_ETF_IOPV, new DecoderInfo(FID_ETF_IOPV, null, FKEY_ETF_IOPV, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_CAS_STATUS, new DecoderInfo(FID_CAS_STATUS, null, FKEY_CAS_STATUS, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_HK_SZ_STK_CONNECT, new DecoderInfo(FID_HK_SZ_STK_CONNECT, null, FKEY_HK_SZ_STK_CONNECT, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_DAY_CLOSE, new DecoderInfo(FID_DAY_CLOSE, null, FKEY_DAY_CLOSE, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_TURNOVER_RATE, new DecoderInfo(FID_TURNOVER_RATE, Arrays.asList("324", "38"), FKEY_TURNOVER_RATE, TurnoverRateDecoder.uniqueId, new TurnoverRateDecoder()));
        put(FID_ORDER_RATIOAH, new DecoderInfo(FID_ORDER_RATIOAH, Arrays.asList("318"), FKEY_ORDER_RATIOAH, OrderRatioAHDecoder.uniqueId, new OrderRatioAHDecoder()));
        put(FID_MINUTES_1, new DecoderInfo(FID_MINUTES_1, Arrays.asList("159"), FKEY_CHART_TRANSQUEUE, MinuteChartDecoder.uniqueId, new MinuteChartDecoder()));
        put(FID_MINUTES_1S, new DecoderInfo(FID_MINUTES_1S, Arrays.asList("159"), FKEY_CHART_TRANSQUEUE, MinuteChartDecoder.uniqueId, new MinuteChartDecoder()));
        put(FID_MINUTES_3, new DecoderInfo(FID_MINUTES_3, Arrays.asList("159"), FKEY_CHART_TRANSQUEUE, MinuteChartDecoder.uniqueId, new MinuteChartDecoder()));
        put(FID_MINUTES_3S, new DecoderInfo(FID_MINUTES_3S, Arrays.asList("159"), FKEY_CHART_TRANSQUEUE, MinuteChartDecoder.uniqueId, new MinuteChartDecoder()));
        put(FID_MINUTES_5, new DecoderInfo(FID_MINUTES_5, Arrays.asList("159"), FKEY_CHART_TRANSQUEUE, MinuteChartDecoder.uniqueId, new MinuteChartDecoder()));
        put(FID_MINUTES_5S, new DecoderInfo(FID_MINUTES_5S, Arrays.asList("159"), FKEY_CHART_TRANSQUEUE, MinuteChartDecoder.uniqueId, new MinuteChartDecoder()));
        put(FID_MINUTES_5S1, new DecoderInfo(FID_MINUTES_5S1, Arrays.asList("159"), FKEY_CHART_TRANSQUEUE, MinuteChartDecoder.uniqueId, new MinuteChartDecoder()));
        put(FID_MINUTES_5S2, new DecoderInfo(FID_MINUTES_5S2, Arrays.asList("159"), FKEY_CHART_TRANSQUEUE, MinuteChartDecoder.uniqueId, new MinuteChartDecoder()));
        put(FID_MINUTES_10, new DecoderInfo(FID_MINUTES_10, Arrays.asList("159"), FKEY_CHART_TRANSQUEUE, MinuteChartDecoder.uniqueId, new MinuteChartDecoder()));
        put(FID_MINUTES_15, new DecoderInfo(FID_MINUTES_15, Arrays.asList("159"), FKEY_CHART_TRANSQUEUE, MinuteChartDecoder.uniqueId, new MinuteChartDecoder()));
        put(FID_MINUTES_30, new DecoderInfo(FID_MINUTES_30, Arrays.asList("159"), FKEY_CHART_TRANSQUEUE, MinuteChartDecoder.uniqueId, new MinuteChartDecoder()));
        put(FID_MINUTES_60, new DecoderInfo(FID_MINUTES_60, Arrays.asList("159"), FKEY_CHART_TRANSQUEUE, MinuteChartDecoder.uniqueId, new MinuteChartDecoder()));
        put(FID_S_1MIN, new DecoderInfo(FID_S_1MIN, Arrays.asList("159"), FKEY_CHART_TRANSQUEUE, MinuteChartDecoder.uniqueId, new MinuteChartDecoder()));
        put(FID_NS_1MIN, new DecoderInfo(FID_NS_1MIN, Arrays.asList("82"), FKEY_CHART_TRANSQUEUE, MinuteChartDecoder.uniqueId, new MinuteChartDecoder()));
        put(FID_S_5MIN, new DecoderInfo(FID_S_5MIN, Arrays.asList("161"), FKEY_CHART_TRANSQUEUE, MinuteChartDecoder.uniqueId, new MinuteChartDecoder()));
        put(FID_NS_5MIN, new DecoderInfo(FID_NS_5MIN, Arrays.asList("82"), FKEY_CHART_TRANSQUEUE, MinuteChartDecoder.uniqueId, new MinuteChartDecoder()));
        put(FID_S_15MIN, new DecoderInfo(FID_S_15MIN, Arrays.asList("161"), FKEY_CHART_TRANSQUEUE, MinuteChartDecoder.uniqueId, new MinuteChartDecoder()));
        put(FID_NS_15MIN, new DecoderInfo(FID_NS_15MIN, Arrays.asList("82"), FKEY_CHART_TRANSQUEUE, MinuteChartDecoder.uniqueId, new MinuteChartDecoder()));
        put(FID_S_30MIN, new DecoderInfo(FID_S_30MIN, Arrays.asList("161"), FKEY_CHART_TRANSQUEUE, MinuteChartDecoder.uniqueId, new MinuteChartDecoder()));
        put(FID_NS_30MIN, new DecoderInfo(FID_NS_30MIN, Arrays.asList("82"), FKEY_CHART_TRANSQUEUE, MinuteChartDecoder.uniqueId, new MinuteChartDecoder()));
        put(FID_S_60MIN, new DecoderInfo(FID_S_60MIN, Arrays.asList("161"), FKEY_CHART_TRANSQUEUE, MinuteChartDecoder.uniqueId, new MinuteChartDecoder()));
        put(FID_NS_60MIN, new DecoderInfo(FID_NS_60MIN, Arrays.asList("82"), FKEY_CHART_TRANSQUEUE, MinuteChartDecoder.uniqueId, new MinuteChartDecoder()));
        put(FID_TICK, new DecoderInfo(FID_TICK, Arrays.asList("161"), FKEY_TICK, TickChartDecoder.uniqueId, new TickChartDecoder()));
        put(FID_TRANSQUEUE, new DecoderInfo(FID_TRANSQUEUE, Arrays.asList("161"), FKEY_TRANSQUEUE, TransactionDecoder.uniqueId, new TransactionDecoder()));
        put(FID_D_TRANSQUEUE, new DecoderInfo(FID_D_TRANSQUEUE, Arrays.asList("161"), FKEY_TRANSQUEUE, TransactionDecoder.uniqueId, new TransactionDecoder()));
        put(FID_TRANSACTION, new DecoderInfo(FID_TRANSACTION, Arrays.asList("161"), FKEY_TRANSQUEUE, TransactionDecoder.uniqueId, new TransactionDecoder()));
        put(FID_ORDER_RATIO, new DecoderInfo(FID_ORDER_RATIO, Arrays.asList("241"), FKEY_ORDER_RATIO, OrderRatioDecoder.uniqueId, new OrderRatioDecoder()));
        put(FID_LIMIT_UP, new DecoderInfo(FID_LIMIT_UP, Arrays.asList("49", "117", "315"), FKEY_LIMIT_UP, LimitUpDecoder.uniqueId, new LimitUpDecoder()));
        put(FID_LIMIT_DOWN, new DecoderInfo(FID_LIMIT_DOWN, Arrays.asList("49", "117", "315"), FKEY_LIMIT_DOWN, LimitDownDecoder.uniqueId, new LimitDownDecoder()));
        put(FID_FLUCTUATION, new DecoderInfo(FID_FLUCTUATION, Arrays.asList("41", "42", "49"), FKEY_FLUCTUATION, FluctuationDecoder.uniqueId, new FluctuationDecoder()));
        put(FID_DATA4MONEYFLOW, new DecoderInfo(FID_DATA4MONEYFLOW, null, FKEY_DATA4MONEYFLOW, MoneyFlowDecoder.uniqueId, new MoneyFlowDecoder()));
        put(FID_DATA4SHORTSELL, new DecoderInfo(FID_DATA4SHORTSELL, null, FKEY_DATA4SHORTSELL, ShortSellDecoder.uniqueId, new ShortSellDecoder()));
        put(FID_DATA4WARRANT, new DecoderInfo(FID_DATA4WARRANT, null, FKEY_DATA4WARRANT, ChartWarDecoder.uniqueId, new ChartWarDecoder()));
        put(FID_DATA4H, new DecoderInfo(FID_DATA4H, Arrays.asList("38", "34", "54", "41", "42"), FKEY_DATA4H, DayChartDecoder.uniqueId, new DayChartDecoder()));
        put(FID_DATA4A, new DecoderInfo(FID_DATA4A, Arrays.asList("38", "34", "54", "41", "42"), FKEY_DATA4A, DayChartDecoder.uniqueId, new DayChartDecoder()));
        put(FID_PREMIUM4AH, new DecoderInfo(FID_PREMIUM4AH, Arrays.asList("38", "34", "54", "41", "42"), FKEY_PREMIUM4AH, DayChartDecoder.uniqueId, new DayChartDecoder()));
        put(FID_S_DAY, new DecoderInfo(FID_S_DAY, Arrays.asList("38", "34", "54", "41", "42"), FKEY_DAYBAR, DayChartDecoder.uniqueId, new DayChartDecoder()));
        put(FID_S_WEEK, new DecoderInfo(FID_S_WEEK, Arrays.asList("38", "34", "54", "41", "42"), FKEY_DAYBAR, DayChartDecoder.uniqueId, new DayChartDecoder()));
        put(FID_S_MONTH, new DecoderInfo(FID_S_MONTH, Arrays.asList("38", "34", "54", "41", "42"), FKEY_DAYBAR, DayChartDecoder.uniqueId, new DayChartDecoder()));
        put(FID_S_YEAR, new DecoderInfo(FID_S_YEAR, Arrays.asList("38", "34", "54", "41", "42"), FKEY_DAYBAR, DayChartDecoder.uniqueId, new DayChartDecoder()));
        put(FID_NS_DAY, new DecoderInfo(FID_NS_DAY, Arrays.asList("38", "34", "54", "41", "42"), FKEY_DAYBAR, DayChartDecoder.uniqueId, new DayChartDecoder()));
        put(FID_NS_WEEK, new DecoderInfo(FID_NS_WEEK, Arrays.asList("38", "34", "54", "41", "42"), FKEY_DAYBAR, DayChartDecoder.uniqueId, new DayChartDecoder()));
        put(FID_NS_MONTH, new DecoderInfo(FID_NS_MONTH, Arrays.asList("38", "34", "54", "41", "42"), FKEY_DAYBAR, DayChartDecoder.uniqueId, new DayChartDecoder()));
        put(FID_NS_YEAR, new DecoderInfo(FID_NS_YEAR, Arrays.asList("38", "34", "54", "41", "42"), FKEY_DAYBAR, DayChartDecoder.uniqueId, new DayChartDecoder()));
        put(FID_O_NORMINAL, new DecoderInfo(FID_O_NORMINAL, Arrays.asList("34"), FKEY_O_NORMINAL, OptionDecoder.uniqueId, new OptionDecoder()));
        put(FID_O_VOL, new DecoderInfo(FID_O_VOL, Arrays.asList("38"), FKEY_O_VOL, OptionDecoder.uniqueId, new OptionDecoder()));
        put(FID_O_CHG, new DecoderInfo(FID_O_CHG, Arrays.asList("40"), FKEY_O_CHG, OptionDecoder.uniqueId, new OptionDecoder()));
        put(FID_O_HIGH, new DecoderInfo(FID_O_HIGH, Arrays.asList("41"), FKEY_O_HIGH, OptionDecoder.uniqueId, new OptionDecoder()));
        put(FID_O_LOW, new DecoderInfo(FID_O_LOW, Arrays.asList("42"), FKEY_O_LOW, OptionDecoder.uniqueId, new OptionDecoder()));
        put(FID_O_PRV_CLOSE, new DecoderInfo(FID_O_PRV_CLOSE, Arrays.asList("49"), FKEY_O_PRV_CLOSE, OptionDecoder.uniqueId, new OptionDecoder()));
        put(FID_O_ASK, new DecoderInfo(FID_O_ASK, Arrays.asList("52"), FKEY_O_ASK, OptionDecoder.uniqueId, new OptionDecoder()));
        put(FID_O_BID, new DecoderInfo(FID_O_BID, Arrays.asList("53"), FKEY_O_BID, OptionDecoder.uniqueId, new OptionDecoder()));
        put(FID_O_OPEN, new DecoderInfo(FID_O_OPEN, Arrays.asList("54"), FKEY_O_OPEN, OptionDecoder.uniqueId, new OptionDecoder()));
        put(FID_O_BIDASK, new DecoderInfo(FID_O_BIDASK, Arrays.asList("119"), FKEY_O_BIDASK, OptionDecoder.uniqueId, new OptionDecoder()));
        put(FID_O_LAST_QTY, new DecoderInfo(FID_O_LAST_QTY, Arrays.asList("121"), FKEY_O_LAST_QTY, OptionDecoder.uniqueId, new OptionDecoder()));
        put(FID_O_LASTINDICATOR, new DecoderInfo(FID_O_LASTINDICATOR, Arrays.asList("122"), FKEY_O_LASTINDICATOR, OptionDecoder.uniqueId, new OptionDecoder()));
        put(FID_O_PRE_VOL, new DecoderInfo(FID_O_PRE_VOL, Arrays.asList("123"), FKEY_O_PRE_VOL, OptionDecoder.uniqueId, new OptionDecoder()));
        put(FID_O_CHGVOL, new DecoderInfo(FID_O_CHGVOL, Arrays.asList("124"), FKEY_O_CHGVOL, OptionDecoder.uniqueId, new OptionDecoder()));
        put(FID_O_GOI, new DecoderInfo(FID_O_GOI, Arrays.asList("125"), FKEY_O_GOI, OptionDecoder.uniqueId, new OptionDecoder()));
        put(FID_O_NOI, new DecoderInfo(FID_O_NOI, Arrays.asList("126"), FKEY_O_NOI, OptionDecoder.uniqueId, new OptionDecoder()));
        put(FID_O_CHGGOI, new DecoderInfo(FID_O_CHGGOI, Arrays.asList("127"), FKEY_O_CHGGOI, OptionDecoder.uniqueId, new OptionDecoder()));
        put(FID_O_CHGNOI, new DecoderInfo(FID_O_CHGNOI, Arrays.asList("128"), FKEY_O_CHGNOI, OptionDecoder.uniqueId, new OptionDecoder()));
        put(FID_TRANSSUM, new DecoderInfo(FID_TRANSSUM, null, FKEY_TRANSSUM, TransSummaryDecoder.uniqueId, new TransSummaryDecoder()));
        put(FID_HOT_SECTORS, new DecoderInfo(FID_HOT_SECTORS, Arrays.asList("108"), FKEY_HOT_SECTORS, HotSectorDecoder.uniqueId, new HotSectorDecoder()));
        put(FID_DAILY_QUOTA_DATA, new DecoderInfo(FID_DAILY_QUOTA_DATA, Arrays.asList("Q1"), FKEY_DAILY_QUOTA_DATA, DailyQuotaDataDecoder.uniqueId, new DailyQuotaDataDecoder()));
        put(FID_MONTHLY_QUOTA_DATA, new DecoderInfo(FID_MONTHLY_QUOTA_DATA, Arrays.asList("Q2"), FKEY_MONTHLY_QUOTA_DATA, MonthlyQuotaDataDecoder.uniqueId, new MonthlyQuotaDataDecoder()));
        put(FID_T10_STKCNT_TRN, new DecoderInfo(FID_T10_STKCNT_TRN, Arrays.asList("Q3"), FKEY_T10_STKCNT_TRN, Top10StockConnectTurnoverDecoder.uniqueId, new Top10StockConnectTurnoverDecoder()));
        put(FID_EXCHANGE_CODE, new DecoderInfo(FID_EXCHANGE_CODE, null, FKEY_EXCHANGE_CODE, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_ALL_DIVIDEND_ANNOUNCE, new DecoderInfo(FID_ALL_DIVIDEND_ANNOUNCE, null, FKEY_ALL_DIVIDEND_ANNOUNCE, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_OPERATING_REVEUE_PERSHARE, new DecoderInfo(FID_OPERATING_REVEUE_PERSHARE, null, FKEY_OPERATING_REVEUE_PERSHARE, LongDecoder.uniqueId, new LongDecoder()));
        put(FID_BOOKVALUE_PERSHARE, new DecoderInfo(FID_BOOKVALUE_PERSHARE, null, FKEY_BOOKVALUE_PERSHARE, LongDecoder.uniqueId, new LongDecoder()));
        put(FID_CASHFLOW_YIELD, new DecoderInfo(FID_CASHFLOW_YIELD, null, FKEY_CASHFLOW_YIELD, LongDecoder.uniqueId, new LongDecoder()));
        put(FID_ENTERPRISE_VALUE, new DecoderInfo(FID_ENTERPRISE_VALUE, null, FKEY_ENTERPRISE_VALUE, LongDecoder.uniqueId, new LongDecoder()));
        put(FID_REVENUE, new DecoderInfo(FID_REVENUE, null, FKEY_REVENUE, LongDecoder.uniqueId, new LongDecoder()));
        put(FID_MS_EARNINGS_PERSHARE, new DecoderInfo(FID_MS_EARNINGS_PERSHARE, null, FKEY_MS_EARNINGS_PERSHARE, LongDecoder.uniqueId, new LongDecoder()));
        put(FID_MS_FORWARDEST_EPS, new DecoderInfo(FID_MS_FORWARDEST_EPS, null, FKEY_MS_FORWARDEST_EPS, LongDecoder.uniqueId, new LongDecoder()));
        put(FID_MS_MEDBUSINESS_DESC, new DecoderInfo(FID_MS_MEDBUSINESS_DESC, null, FKEY_MS_MEDBUSINESS_DESC, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_PREVOLUME, new DecoderInfo(FID_PREVOLUME, null, FKEY_PREVOLUME, LongDecoder.uniqueId, new LongDecoder()));
        put(FID_POSTVOLUME, new DecoderInfo(FID_POSTVOLUME, null, FKEY_POSTVOLUME, LongDecoder.uniqueId, new LongDecoder()));
        put(FID_CUSIP, new DecoderInfo(FID_CUSIP, null, FKEY_CUSIP, LongDecoder.uniqueId, new LongDecoder()));
        put(FID_GENERAL_INSTRU_STATUS, new DecoderInfo(FID_GENERAL_INSTRU_STATUS, null, FKEY_GENERAL_INSTRU_STATUS, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_MSINDCD, new DecoderInfo(FID_MSINDCD, null, FKEY_MSINDCD, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_LOWER_STRIKE_PRICE, new DecoderInfo(FID_LOWER_STRIKE_PRICE, null, FKEY_LOWER_STRIKE_PRICE, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_UPPER_STRIKE_PRICE, new DecoderInfo(FID_UPPER_STRIKE_PRICE, null, FKEY_UPPER_STRIKE_PRICE, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_IN_THE_RANGE_PAYMENT, new DecoderInfo(FID_IN_THE_RANGE_PAYMENT, null, FKEY_IN_THE_RANGE_PAYMENT, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_OUT_OF_THE_RANGE_PAYMENT, new DecoderInfo(FID_OUT_OF_THE_RANGE_PAYMENT, null, FKEY_OUT_OF_THE_RANGE_PAYMENT, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_POTENTIAL_RETURN, new DecoderInfo(FID_POTENTIAL_RETURN, null, FKEY_POTENTIAL_RETURN, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_UPPER_STRIKE_DISTANCE, new DecoderInfo(FID_UPPER_STRIKE_DISTANCE, null, FKEY_UPPER_STRIKE_DISTANCE, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_UPPER_STRIKE_DISTANCE_RATE, new DecoderInfo(FID_UPPER_STRIKE_DISTANCE_RATE, null, FKEY_UPPER_STRIKE_DISTANCE_RATE, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_LOWER_STRIKE_DISTANCE, new DecoderInfo(FID_LOWER_STRIKE_DISTANCE, null, FKEY_LOWER_STRIKE_DISTANCE, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_LOWER_STRIKE_DISTANCE_RATE, new DecoderInfo(FID_LOWER_STRIKE_DISTANCE_RATE, null, FKEY_LOWER_STRIKE_DISTANCE_RATE, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_STRIK_EDISTANCE_RATE, new DecoderInfo(FID_STRIK_EDISTANCE_RATE, null, FKEY_STRIK_EDISTANCE_RATE, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_IS_IN_THE_RANGE, new DecoderInfo(FID_IS_IN_THE_RANGE, null, FKEY_IS_IN_THE_RANGE, StringDecoder.uniqueId, new StringDecoder()));
        put(FID_STRIKE_WIDTH, new DecoderInfo(FID_STRIKE_WIDTH, null, FKEY_STRIKE_WIDTH, DoubleDecoder.uniqueId, new DoubleDecoder()));
        put(FID_B1, new DecoderInfo(FID_B1, null, FID_B1, IndustryAnalysisDecoder.uniqueId, new IndustryAnalysisDecoder()));
        put(FID_B2, new DecoderInfo(FID_B2, null, FID_B2, SpeStkDecoder.uniqueId, new SpeStkDecoder()));
        put(FID_B3, new DecoderInfo(FID_B3, null, FID_B3, SpeFlowDecoder.uniqueId, new SpeFlowDecoder()));
        put(FID_B4, new DecoderInfo(FID_B4, null, FID_B4, SpeFlowDecoder.uniqueId, new SpeFlowDecoder()));
        put(FID_B5, new DecoderInfo(FID_B5, null, FID_B5, SpeBroDecoder.uniqueId, new SpeBroDecoder()));
        put(FID_B6, new DecoderInfo(FID_B6, null, FID_B6, SpeFlowDecoder.uniqueId, new SpeFlowDecoder()));
        put(FID_B7, new DecoderInfo(FID_B7, null, FID_B7, SpeFlowDecoder.uniqueId, new SpeFlowDecoder()));
        put(FID_B8, new DecoderInfo(FID_B8, null, FID_B8, RegionDecoder.uniqueId, new RegionDecoder()));
        put(FID_B9, new DecoderInfo(FID_B9, null, FID_B9, SpeBroDecoder.uniqueId, new SpeBroDecoder()));
        put(FID_ASA_HK, new DecoderInfo(FID_ASA_HK, null, "", StringDecoder.uniqueId, new StringDecoder()));
    }};


}
